apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tektoncd-nodejs-tutorial-task
spec:
  inputs:
    resources:
      - name: tektoncd-nodejs-tutorial-resources
        type: git
  steps:
    - name: npm-echo-message
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - echo "NPM started!"
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm install
      workingDir: /workspace/tektoncd-nodejs-tutorial-resources
    - name: npm-build
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/tektoncd-nodejs-tutorial-resources
    - name: build-push-image
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/workspace/tektoncd-nodejs-tutorial-resources/Dockerfile
        - --destination=docker-registry.default.svc:5000/web-backend/tektoncd-nodejs-tutorial:latest
        - --context=/workspace/tektoncd-nodejs-tutorial-resources
        - --skip-tls-verify
    - name: run-image
      image: ebits/openshift-client
      command: ["oc"]
      args:
        - create
        - -f
        - /workspace/tektoncd-nodejs-tutorial-resources/openshift/
